### ISSUE TITLE
Question: Azure vs Azure Solid

### ISSUE THREAD

**Issue by Vistaus** [vinceliuice/Azure-theme#2]
Quick question: what's the difference between Azure and Azure Solid? 'Cause I don't notice any difference.

**Comment by vinceliuice** [comment]
Azure has transparent headerbar and sidebar （maybe a little transparent is hard to notice）
But Azure Solid do not have any transparent part

**Comment by Vistaus** [comment]
Ah, I see, thanks for the explanation! :)
