### ISSUE TITLE
Make Title bar less vertical padding.

### ISSUE THREAD

**Issue by aazkan** [vinceliuice/Azure-theme#3]
Hello, 
First off thank you for a beautiful theme. I have a smallish laptop screen, 1280 x 800. What should I change so that the title bar is more compact? If there is no way to change overall compact-ness I would settle for a not so tall vertical padding. For example this one below:

![screengrab-2017-09-08_10-27-vertical-padding-azure](https://user-images.githubusercontent.com/22463221/30193586-840d9fb2-9480-11e7-8dbb-4c97e2ef8e2a.png)

Thank you for your reply.

**Comment by vinceliuice** [comment]
headerbar,
%titlebar {
  min-height: 42px;
  padding: 0 10px;
-------------------------------------
You should change the min-height size of headerbar

**Comment by aazkan** [comment]
Dear vinceliuice,

Thank you! (bow)

Rgds.
