### ISSUE TITLE
Cannot find menubar-toolbar-*.rc

### ISSUE THREAD

**Issue by FioneraGH** [vinceliuice/Azure-theme#4]
Azure/gtk-2.0/gtkrc:24: cannot find included file：“menubar-toolbar/menubar-toolbar.rc”. Its in gtk-2.0 dic.

**Comment by vinceliuice** [comment]
You should use the install script to install azure, The install script will copy menubar-toolbar.rc to menubar-toolbar/menubar-toolbar.rc

**Comment by FioneraGH** [comment]
@vinceliuice thanks:)
